// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Robin.Extensions.WordCloud.CompiledModels
{
    public partial class WordCloudDbContextModel
    {
        partial void Initialize()
        {
            var record = RecordEntityType.Create(this);

            RecordEntityType.CreateAnnotations(record);

            AddAnnotation("ProductVersion", "8.0.4");
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var record = FindEntityType("Robin.Extensions.WordCloud.Record")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            record.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var robinExtensionsWordCloudRecordTableBase = new TableBase("Robin.Extensions.WordCloud.Record", null, relationalModel);
            var contentColumnBase = new ColumnBase<ColumnMappingBase>("Content", "TEXT", robinExtensionsWordCloudRecordTableBase);
            robinExtensionsWordCloudRecordTableBase.Columns.Add("Content", contentColumnBase);
            var groupIdColumnBase = new ColumnBase<ColumnMappingBase>("GroupId", "INTEGER", robinExtensionsWordCloudRecordTableBase);
            robinExtensionsWordCloudRecordTableBase.Columns.Add("GroupId", groupIdColumnBase);
            var recordIdColumnBase = new ColumnBase<ColumnMappingBase>("RecordId", "INTEGER", robinExtensionsWordCloudRecordTableBase);
            robinExtensionsWordCloudRecordTableBase.Columns.Add("RecordId", recordIdColumnBase);
            relationalModel.DefaultTables.Add("Robin.Extensions.WordCloud.Record", robinExtensionsWordCloudRecordTableBase);
            var robinExtensionsWordCloudRecordMappingBase = new TableMappingBase<ColumnMappingBase>(record, robinExtensionsWordCloudRecordTableBase, true);
            robinExtensionsWordCloudRecordTableBase.AddTypeMapping(robinExtensionsWordCloudRecordMappingBase, false);
            defaultTableMappings.Add(robinExtensionsWordCloudRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)recordIdColumnBase, record.FindProperty("RecordId")!, robinExtensionsWordCloudRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)contentColumnBase, record.FindProperty("Content")!, robinExtensionsWordCloudRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)groupIdColumnBase, record.FindProperty("GroupId")!, robinExtensionsWordCloudRecordMappingBase);

            var tableMappings = new List<TableMapping>();
            record.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var recordsTable = new Table("Records", null, relationalModel);
            var recordIdColumn = new Column("RecordId", "INTEGER", recordsTable);
            recordsTable.Columns.Add("RecordId", recordIdColumn);
            var contentColumn = new Column("Content", "TEXT", recordsTable);
            recordsTable.Columns.Add("Content", contentColumn);
            var groupIdColumn = new Column("GroupId", "INTEGER", recordsTable);
            recordsTable.Columns.Add("GroupId", groupIdColumn);
            var pK_Records = new UniqueConstraint("PK_Records", recordsTable, new[] { recordIdColumn });
            recordsTable.PrimaryKey = pK_Records;
            var pK_RecordsUc = RelationalModel.GetKey(this,
                "Robin.Extensions.WordCloud.Record",
                new[] { "RecordId" });
            pK_Records.MappedKeys.Add(pK_RecordsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_RecordsUc).Add(pK_Records);
            recordsTable.UniqueConstraints.Add("PK_Records", pK_Records);
            relationalModel.Tables.Add(("Records", null), recordsTable);
            var recordsTableMapping = new TableMapping(record, recordsTable, true);
            recordsTable.AddTypeMapping(recordsTableMapping, false);
            tableMappings.Add(recordsTableMapping);
            RelationalModel.CreateColumnMapping(recordIdColumn, record.FindProperty("RecordId")!, recordsTableMapping);
            RelationalModel.CreateColumnMapping(contentColumn, record.FindProperty("Content")!, recordsTableMapping);
            RelationalModel.CreateColumnMapping(groupIdColumn, record.FindProperty("GroupId")!, recordsTableMapping);
            return relationalModel.MakeReadOnly();
        }
    }
}
